### PR TITLE
Fixed Permissions Probelms

### PR DESCRIPTION
**Pull request by maheshuligade**
There was problem of permissions when installing this script.

### CODE REVIEW

**Comment by pbhopalka** [comment]
It is usually advised not to use `sudo` while using pip. Shrimadhav explains it in his [blog](https://blog.shrimadhavuk.me/posts/2017/03/14/to-sudo-or-not-to-sudo/) and I agree with this. That's why I don't want this repository to have `sudo` in the scripts (wherever possible).

If it is ok with you @maheshuligade , you may close this request without merging it. :)

**Comment by maheshuligade** [comment]
I agree with what you are saying, but there are some libraries in that script which doesn't install without sudo (unless you are using anaconda.)

**Comment by pbhopalka** [comment]
I think, we should rather mention in the Readme and the script that a python container (like Ananconda) is expected to be installed and give a link to do that. This would not mess up the other scripts/ softwares already running or installed in the system.

**Comment by maheshuligade** [comment]
Added Note about Anaconda and Improved Some design.

**Comment by maheshuligade** [comment]
Added Note about Anaconda and Improved Some design.

**Comment by maheshuligade** [comment]
Added Note about Anaconda and Improved Some design.

**Pull request closed without merging**
